Sys.setlocale("LC_TIME","English")
dat<-read.table("./household_power_consumption.txt",sep=";",header=TRUE)
a<-subset(dat,dat$Date=="1/2/2007" | dat$Date=="2/2/2007")
Gap<-as.numeric(paste(a$Global_active_power))
Time<-paste(as.character(a$Date),a$Time)
y<-strptime(Time,"%d/%m/%Y %H:%M:%S")

png(file="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(y,Gap,ylab="Global Active Power (kilowatts)",type="l",xlab="")
plot(y,as.numeric(paste(a$Voltage)),type="l",ylab = "Voltage",xlab = "datetime")
plot(y,as.numeric(paste(a$Sub_metering_1)),type="l",col="black",xlab="",ylab="Energy sub metering")
lines(y,as.numeric(paste(a$Sub_metering_2)),col="red")
lines(y,as.numeric(paste(a$Sub_metering_3)),col="blue")
legend("topright",lty=c(1,1,1),lwd=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
axis(side=2,at=seq(0,35,by=10),labels=seq(0,30,by=10))
plot(y,as.numeric(paste(a$Global_reactive_power)),type="l",ylab = "Global_reactive_power",xlab = "datetime")
dev.off()
